#!/bin/zsh
#   __ _| (_) __ _ ___
#  / _` | | |/ _` / __|
# | (_| | | | (_| \__ \
#  \__,_|_|_|\__,_|___/

# safer defaults
alias cp='cp -riv'
alias mv='mv -iv'
alias rm='rm -vI'
alias mkdir='mkdir -pv'
alias rsync='rsync -uvrP'

# logo-ls
alias l='logo-ls -v'
alias la='logo-ls -Av'
alias ll='logo-ls -vlgh'

# use nvim
alias vi='/usr/bin/vim -u NONE'
alias vim='nvim'

# rust replacements
alias cat='bat'
alias grep='rg'

# navigate to directories with ranger
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'

# ssh in kitty
alias ssh='kitty +kitten ssh'

# change wallpaper
function chwal {
    IMG_DIR="$HOME/Pictures/Wallpapers"
    WAL=$(randfile "$IMG_DIR")
    feh --bg-fill "$IMG_DIR/$WAL" 2> /dev/null
}

# change wallpaper to Linux Mint default wallpapers
function norm {
    IMG_DIR="/usr/share/backgrounds/linuxmint-combined"
    WAL=$(randfile "$IMG_DIR")
    feh --bg-fill "$IMG_DIR/$WAL"
}

# change wallpaper to specific image
function bkg() {
    feh --bg-fill "$1"
}

# set terminal tab names
function title() {
    echo -e "set title: $1\033]0;$@\007"
}
