#!/bin/zsh
#   __ _| (_) __ _ ___
#  / _` | | |/ _` / __|
# | (_| | | | (_| \__ \
#  \__,_|_|_|\__,_|___/

# safer defaults
alias cp='rsync -aurvhP --progress'
alias mv='mv -iv'
alias rm='rm -vI'
alias mkdir='mkdir -pv'

# logo-ls
alias l='logo-ls -v'
alias la='logo-ls -Av'
alias ll='logo-ls -vlgh'

# use nvim
alias vi='/usr/bin/vim -u NONE'
alias vim='nvim'

# rust replacements
alias cat='bat'
alias grep='rg'

# navigate to directories with ranger
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'

# change wallpaper (Cinnamon)
function bkg() {
    gsettings set org.cinnamon.desktop.background picture-uri "file:///$1"
}

# change wallpaper
function chwal {
    IMG_DIR="$HOME/Pictures/Wallpapers"
    WAL=$(randfile "$IMG_DIR")
    bkg "$IMG_DIR/$WAL"
}

# change wallpaper (/usr/share/backgrounds/wallpapers)
function norm {
    IMG_DIR="/usr/share/backgrounds/wallpapers"
    WAL=$(randfile "$IMG_DIR")
    bkg "$IMG_DIR/$WAL"
}
