#  _               _        _               _
# | |__   __ _ ___(_) ___  | |__   __ _ ___| |__
# | '_ \ / _` / __| |/ __| | '_ \ / _` / __| '_ \
# | |_) | (_| \__ \ | (__  | |_) | (_| \__ \ | | |
# |_.__/ \__,_|___/_|\___| |_.__/ \__,_|___/_| |_|

# Set default editor
export EDITOR='vim'
export VISUAL='vim'

# alia-ls-es
alias l='ls'
alias ll='ls -l'
alias la='ls -a'
