"  _               _              _
" | |__   __ _ ___(_) ___  __   _(_)_ __ ___
" | '_ \ / _` / __| |/ __| \ \ / / | '_ ` _ \
" | |_) | (_| \__ \ | (__   \ V /| | | | | | |
" |_.__/ \__,_|___/_|\___|   \_/ |_|_| |_| |_|

" Remap alt
    set <M-j>=j
    set <M-k>=k
    set <M-h>=h
    set <M-l>=l

" Basics
    let mapleader = " "
    inoremap jk <ESC>

    set number
    set relativenumber
    set ignorecase
    set smartcase

    set nocompatible
    set encoding=utf-8
    set showcmd

    syntax on
    filetype plugin on
    filetype indent on

    set wrap
    set redrawtime=10000
    set lazyredraw
    set nolist

    set wildmenu
    set wildmode=longest:full,full

" Enable word movement between separators
    set iskeyword-=_-

" Undo Directory
    set hidden
    set noswapfile
    set nobackup
    set undodir=~/.vim/undodir
    set undofile

" Tabs
    set tabstop=4
    set softtabstop=4
    set shiftwidth=4
    set expandtab
    set autoindent

" Highlight searches and <Leader><Leader> to unhighlight
    set incsearch
    set hlsearch
    nnoremap <silent> <leader><leader> :nohl<CR><C-l>

"Disable auto-commenting
    autocmd FileType * setlocal formatoptions-=c formatoptions-=o

" Remove trailing white space on save
    autocmd BufWritePre * %s/\s\+$//e

" Open folds
    nnoremap <CR> za

" Increment number
    nnoremap <C-p> <C-a>

" Toggle numbers
    nmap <silent> <leader>n :set invnumber<CR>:set invrelativenumber<CR>

" Toggle spell
    nnoremap <silent> <leader>s :set invspell spelllang=en_us<cr>

" Yank to end of line
    nnoremap Y y$

" Indentation
    nnoremap <M-h> <<
    nnoremap <M-l> >>
    inoremap <M-h> <C-d>
    inoremap <M-l> <C-t>

" Reselect visual selection after indent
    vnoremap < <gv
    vnoremap > >gv
    vnoremap <M-h> <gv
    vnoremap <M-l> >gv

" Undo breakpoints
    inoremap . .<C-g>u
    inoremap , ,<C-g>u
    inoremap ! !<C-g>u
    inoremap ? ?<C-g>u

" Moving text
    nnoremap <M-j> :m .+1<CR>==
    nnoremap <M-k> :m .-2<CR>==
    inoremap <M-j> <ESC>:m .+1<CR>==gi
    inoremap <M-k> <ESC>:m .-2<CR>==gi
    vnoremap <M-j> :m '>+1<CR>gv=gv
    vnoremap <M-k> :m '<-2<CR>gv=gv

" Fix splits
    set splitbelow splitright

" Vertical Split
    nnoremap <silent> <leader>wv :vnew<CR>
    nnoremap <silent> <leader>wh :wincmd h<CR>
    nnoremap <silent> <leader>wl :wincmd l<CR>

" Horizontal Split
    nnoremap <silent> <leader>ws :new<CR>
    nnoremap <silent> <leader>wj :wincmd j<CR>
    nnoremap <silent> <leader>wk :wincmd k<CR>

" Terminal
    map <Leader>t :term<CR>

" Ctrl + Backspace to Delete Word
    imap <C-H> <C-W>
