"  _               _              _
" | |__   __ _ ___(_) ___  __   _(_)_ __ ___
" | '_ \ / _` / __| |/ __| \ \ / / | '_ ` _ \
" | |_) | (_| \__ \ | (__   \ V /| | | | | | |
" |_.__/ \__,_|___/_|\___|   \_/ |_|_| |_| |_|

" Remap alt
    set <M-j>=j
    set <M-k>=k
    set <M-h>=h
    set <M-l>=l

" Basics
    let mapleader = " "
    inoremap jk <ESC>
    cnoremap jk <C-C>
    cnoremap <C-k> <Up>
    cnoremap <C-j> <Down>

    set number
    set relativenumber
    set ignorecase infercase
    set smartcase

    set nocompatible
    set encoding=utf-8
    set nrformats=
    set showcmd

    syntax on
    filetype plugin on
    filetype indent on

    set wrap
    set redrawtime=10000
    set lazyredraw
    set nolist

    set wildmenu
    set wildmode=longest:full,full
    set history=200

" Prevent escape / alt overlap
    set ttimeoutlen=50

" Fix splits
    set splitbelow splitright

" Splits
    nnoremap <leader>w <C-w>

" Undo Directory
    set hidden
    set noswapfile
    set nobackup
    set undodir=~/.vim/undodir
    set undofile

" Move viminfo
    set viminfo+=n~/.vim/viminfo

" Tabs
    set tabstop=4
    set softtabstop=4
    set shiftwidth=4
    set expandtab
    set autoindent

" Highlight searches and <Leader><Leader> to unhighlight
    set incsearch
    set hlsearch
    nnoremap <silent> <leader><leader> :<C-u>nohl<CR><C-l>

"Disable auto-commenting
    autocmd FileType * setlocal formatoptions-=c formatoptions-=o

" Remove trailing white space on save
    autocmd BufWritePre * %s/\s\+$//e

" Open folds
    nnoremap <CR> za

" Yank to end of line
    nnoremap Y y$

" Indentation
    nnoremap <M-h> <<
    nnoremap <M-l> >>
    inoremap <M-h> <C-d>
    inoremap <M-l> <C-t>

" Reselect visual selection after indent
    vnoremap < <gv
    vnoremap > >gv
    vnoremap <M-h> <gv
    vnoremap <M-l> >gv

" Undo breakpoints
    inoremap . .<C-g>u
    inoremap , ,<C-g>u
    inoremap ! !<C-g>u
    inoremap ? ?<C-g>u

" Moving text
    nnoremap <M-j> :<C-u>m .+1<CR>==
    nnoremap <M-k> :<C-u>m .-2<CR>==
    inoremap <M-j> <ESC>:<C-u>m .+1<CR>==gi
    inoremap <M-k> <ESC>:<C-u>m .-2<CR>==gi
    vnoremap <M-j> :<C-u>m '>+1<CR>gv=gv
    vnoremap <M-k> :<C-u>m '<-2<CR>gv=gv

" Toggle line numbers
    nmap <silent> <leader>tl :<C-u>set invnumber<CR>:<C-u>set invrelativenumber<CR>

" Toggle spell checking
    nnoremap <silent> <leader>ts :<C-u>set invspell spelllang=en_us<CR>

" Netrw
    map <silent> <leader>dd :<C-u>Explore<CR>

" Ctrl + Backspace to Delete Word
    imap <C-H> <C-W>
