#!/bin/bash
# baka: create tar backups of specified directories

SECONDS=0

# exclude file
EXCLUDE="$HOME/Code/Bash/files/baka-exclude"

# save location
# SAVEDIR="/media/ddmin/Roronoa/Enma/"
# SAVEDIR="root@nexus:/root/Vault/Charlie"
SAVEDIR="root@10.0.0.1:/root/Vault/Charlie"

# directories to archive
dirs=("Code" "Documents" "Pictures" "Music")

# loop through directories
for d in ${dirs[@]}; do

    # fancy printing
    len=$((34+${#d}))
    printf '=%.0s' `eval echo {1..$len}`
    echo ""
    echo "#           Archiving $d           #"
    printf '=%.0s' `eval echo {1..$len}`
    echo ""

    # create backup
    rsync -aurvzP --exclude-from="$EXCLUDE" "$HOME/$d" "$SAVEDIR" --delete-after --delete-excluded
done

msg="Finished in $((($SECONDS)/60))m $((($SECONDS)%60))s"
len=$((36+${#d}))
printf '=%.0s' `eval echo {1..$len}`
echo ""
echo "#           $msg           #"
printf '=%.0s' `eval echo {1..$len}`
echo ""
