#!/bin/bash
# baka: create tar backups of specified directories

# make sure you are in the home directory
cd $HOME

FILE='/home/ddmin/Code/Bash/baka'
DIRECTORY="$(dirname "${FILE}")"
SAVEDIR="/media/ddmin/Roronoa/Enma"

if [[ ! -d "$SAVEDIR" ]]; then
    echo "'$SAVEDIR' does not exist."
    exit
fi

# directories to archive
dirs=("Code" "Documents" "Pictures" "Music")

# loop through directories
for d in ${dirs[@]}; do
    save_file=$(echo ${d,,})

    # fancy printing
    len=$((40+${#d}))
    printf '=%.0s' `eval echo {1..$len}`
    echo ""
    echo "#           Creating $save_file.tar.xz           #"
    printf '=%.0s' `eval echo {1..$len}`
    echo ""

    # create tars while excluding directories from files/backup-exclude
    tar -X "$DIRECTORY/files/backup-exclude" -czvf "$SAVEDIR/$save_file.tar.gz" "$d"
done
