#!/bin/bash
# divac: divide and conquer - divide directory into NUM amount of folders with SIZE number of files each

IFS=$'\n' # only separate on newlines
set -e

if [ $# -lt 1 ]; then
    echo "Please provide number of folders."
    echo "USAGE: $(basename $0) [FOLDER-COUNT] [INPUT-DIRECTORY]"
    exit
fi

dir=$2
if [ $# -lt 2 ]; then
    dir="."
fi

amt=$(find ${dir} -maxdepth 1 -type f | wc -l)
fpf=$(($amt / $1))
mod=$(($amt % $1))

# Create Directories
for i in $(seq -f "%02g" 1 $1)
do
    mkdir -p ${dir}/$i

    extra=0
    if [ $mod -gt 0 ]; then
        extra=1
        mod=$(($mod - 1))
    fi

    files=$(find ${dir} -maxdepth 1 -type f | sort -V | head -$((fpf + extra)))
    mv -t ${dir}/$i $files
done

unset IFS
