#!/bin/bash
# emoji-selector: display rofi menu and paste selected emoji

EMOJIS_PATH="$HOME/.config/rofi/emoji-list"

line=`cat $EMOJIS_PATH | rofi -dmenu -markup-rows -p "emoji" -columns 3`
[[ -z $line ]] && exit
a="${line#*>}"
b="${a%:*}"
echo -n $b | xsel -ipb

xdotool key ctrl+shift+v
