#!/bin/bash
# file2pdf: compile text file into pdf

# usage: file2pdf [INPUT FILE] [OUTPUT FILE]

TXT=$1
PDF=$2

echo "Converting $TXT to PDF..."
enscript "$TXT" -B -o - | ps2pdf - "$PDF"
echo "Saved to $PDF"
