#!/bin/bash

# lilo: stitch two images side-by-side and display

echo $@
exit

help() {
    echo "$(basename $0): provide 2 images to stitch together"
    echo "Usage: $(basename $0) [RIGHT] [LEFT]"
}

if [ $# -lt 2 ]; then
    >&2 echo "ERROR: Please provide two files."
    echo
    help
    exit 1
fi

right=$(basename $1)
left=$(basename $2)

ext="${right##*.}"

rbase=${right%.$ext}
lbase=${left%.$ext}


OUTPUT="${rbase}-${lbase}.${ext}"

echo $OUTPUT
convert $left $right +append $OUTPUT
