#!/bin/bash
# lilo: stitch two images side-by-side

set -e

usage() {
    echo
    echo "Usage: $(basename $0) [OPTIONS] [RIGHT] [LEFT]"
    echo "Stitch RIGHT and LEFT images, and save as a new image."
    echo
    echo "  -h              display this message exit"
    echo "  -r              reverse order RIGHT and LEFT"
    echo "  -v              stitch images vertically (default horizontally)"
    echo "  -o              specify output file"
}

if [ $# -lt 2 ]; then
    >&2 echo -e "ERROR: Please provide two files."
    >&2 usage
    exit 1
fi

while getopts ":hvro::" o; do
    case "${o}" in
        h)
            usage
            exit
            ;;
        v)
            vertical=1
            ;;
        r)
            reverse=1
            ;;
        o)
            output=${OPTARG}
            ;;
        *)
            >&2 usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

right=$(basename $1)
left=$(basename $2)

if [ -z $vertical ]; then
    operation="+append"
else
    operation="-append"
fi

if [ -z $reverse ]; then
    temp=$left
    left=$right
    right=$temp
fi

rext="${right##*.}"
lext="${left##*.}"
rbase=${right%.$rext}
lbase=${left%.$lext}

if [ -z $output ]; then
    output="${rbase}-${lbase}.${rext}"
fi

convert $left $right $operation $output
echo $output
