#!/bin/bash
# mocr-scrot: take a screenshot of an area and save to directory

OCR_DIR=/tmp/ocr
mkdir -p $OCR_DIR

scrot --select \
    --ignorekeyboard \
    --line color=green \
    $OCR_DIR/`date +"manga-ocr-%Y-%m-%d_%T.png"` || exit 1

# gnome
# gnome-screenshot -a -f $OCR_DIR/`date +"manga-ocr-%Y-%m-%d_%T.png"` || exit 1

# xfce
# xfce4-screenshooter -r -s $OCR_DIR/`date +"manga-ocr-%Y-%m-%d_%T.png"` || exit 1
