#!/bin/bash
# mocr-scrot: take a screenshot of an area and save to directory

OCR_DIR=/tmp/ocr
mkdir -p $OCR_DIR

slop=$(slop -c 0,15,0 -f "%g") || exit 1
read -r G <<< $slop
import -window root -crop $G $OCR_DIR/`date +"manga-ocr-%Y-%m-%d_%T.png"`
