#!/bin/bash
# autocompile md to pdf

filename=$1
target="$(dirname "${filename}")/pdf"
output="$(basename "$filename" .md).pdf"

mkdir -p $target

pandoc \
    --latex-engine=xelatex \
    -o "$target/$output" "$filename" &

echo "$target/$output" > /tmp/lasteditpdf.txt
