#!/bin/bash

# ocr: tesseract wrapper

set -e

language=`tesseract --list-langs | \
    tail -n +2 | \
    tr '\n' '\0' | \
    xargs -0 -n 1 basename | \
    rofi -dmenu -p "language" 2> /dev/null`

OCR_DIR="/tmp/tesseract-ocr"
mkdir -p $OCR_DIR

filename=`date +"tesseract-%Y-%m-%d_%T"`

# gnome
# gnome-screenshot -a -f $OCR_DIR/$filename.png || exit 1

# xfce
xfce4-screenshooter -r -s "$OCR_DIR"/"$filename.png" || exit 1

tesseract -l $language "$OCR_DIR"/"$filename.png" "$OCR_DIR"/"$filename"
cat "$OCR_DIR"/"$filename.txt" | xsel -bi
