#!/bin/bash

# ocr: tesseract wrapper

language="$1"
if [ -z $1 ]; then
    language="eng"
fi

OCR_DIR="/tmp/tesseract-ocr"
mkdir -p $OCR_DIR

filename=`date +"tesseract-%Y-%m-%d_%T"`

# gnome
# gnome-screenshot -a -f $OCR_DIR/$filename.png

# xfce
xfce4-screenshooter -r -s "$OCR_DIR"/"$filename.png"

tesseract -l $language "$OCR_DIR"/"$filename.png" "$OCR_DIR"/"$filename"
cat "$OCR_DIR"/"$filename.txt" | xsel -bi