#!/bin/bash

# ocr: tesseract wrapper

set -e

language=`tesseract --list-langs | \
    tail -n +2 | \
    tr '\n' '\0' | \
    xargs -0 -n 1 basename | \
    rofi -dmenu -p "language" 2> /dev/null`

[[ -z $language ]] && exit

OCR_DIR="/tmp/tesseract-ocr"
mkdir -p $OCR_DIR

filename=`date +"tesseract-%Y-%m-%d_%T"`

# gnome
# gnome-screenshot -a -f $OCR_DIR/$filename.png || exit 1

# xfce
xfce4-screenshooter -r -s "$OCR_DIR"/"$filename.png" || exit 1

notify-send -u critical -t 0 -i "$HOME/.icons/tesseract.png" "tesseract-ocr" "tesseract is running..."
tesseract -l $language "$OCR_DIR"/"$filename.png" "$OCR_DIR"/"$filename"

sleep 1
while [ -z "$OCR_DIR/$filename" ]; do
    sleep 1
done

# kill notification
pkill xfce4-notifyd

cat "$OCR_DIR"/"$filename.txt" | sed -r 's///' | xsel -bi
