#!/bin/bash
# sys: catch-all for miscellaneous functions

# Get number of lines
while getopts o: option
do
    case "${option}"
        in
        o) OPTION=${OPTARG};;
    esac
done

function help {
    echo "Usage: sys -o [OPTION]";
    echo "OPTIONS:"
    echo "          cam: attach VirtualBox webcam"
    echo "          mix: mono-audio"
    echo "        sound: reload sound"
}

if [ -z $OPTION ]
then
    help
    exit
fi

case $OPTION in
cam)
    VBoxManage controlvm "Windows 10" webcam attach .2
;;
mix)
    pacmd load-module module-remap-sink sink_name=mono master=alsa_output.pci-0000_00_1f.3.analog-stereo channels=1 channel_map=mono
;;
sound)
    sudo alsa force-reload
;;
*)
    echo "$OPTION is not a valid option"
    help
;;
esac
