#!/bin/bash
# sys: catch-all for miscellaneous functions

dialog --title "sys" --menu "Choose an option:" 15 80 4 \
    cam "attach VirtualBox camera" \
    vpn "toggle VPN" \
    sound "reload audio" \
    mono "enable mono audio" \
    2> /tmp/sys.option

clear
CHOICE=$(cat /tmp/sys.option)

case $CHOICE in

cam)
    echo "cam: attaching camera to Windows 10"
    VBoxManage controlvm "Windows 10" webcam attach .1
;;

sound)
    echo "sound: reloading sound"
    sudo alsa force-reload
;;

mono)
    echo "mono: enabling mono audio"
    pacmd load-module module-remap-sink sink_name=mono master=alsa_output.pci-0000_00_1f.3.analog-stereo channels=1 channel_map=mono
;;

vpn)
    ip a | grep wg0 > /dev/null \
        && echo "vpn: disabling wg0" \
        && sudo wg-quick down wg0 \
        && exit

     echo "vpn: enabling wg0" \
        && sudo wg-quick up wg0 \
        && exit
;;
esac
