#!/bin/bash
# undivac: to undo the work of our predecessors

IFS=$'\n'
set -e

input=$1
if [ $# -lt 1 ]; then
    input="."
fi

for dir in $(find "$input" -mindepth 1 -maxdepth 1 -type d )
do
    mv $(find "$dir" -type f) "$input"/
done

unset IFS
