#!/bin/bash
# toggle protonvpn

function vpnToggle {
    VPN=$(protonvpn s)
    STATUS="$(echo $VPN | grep Connected)"

    # check if VPN is already connected
    if [ -z "$STATUS" ]
    then
        sudo echo "Connecting to VPN..."
        sudo protonvpn c
        exit
    fi
    sudo echo "Disconnecting from VPN..."
    sudo protonvpn d
}

vpnToggle
