#!/bin/bash
# whoer: print ip information from URL

RED="\033[1;31m"
BLUE="\033[1;34m"
NC="\033[0m"

URL="https://am.i.mullvad.net/json"
curl "${URL}" -s |\
    sed 's/:/\t/g' |\
    sed 's/,/\n/g' |\
    sed 's/[\{\}\"]//g' |\
    grep '^ip\|country\|city\|organization' |\
    awk -F'\t' -v red="$RED" -v blue="$BLUE" -v nc="$NC" '{print red $1 nc "\t\t" blue $2 nc}' |\
    column -t -s $'\t'
