#!/bin/bash
# whoer: print ip information from ipinfo.io

curl -s ipinfo.io/json | grep -i '"ip"\|"city"\|"region"\|"country"\|"org"' |\
    column -s '"' -t |\
    awk -F : '{print "\033[1;31m"$1" \033[0m \033[1;36m"$2"\033[0m"}' |\
    sed 's/[,]//g'
